server:
  port: 9090

spring:
  application:
    name: db-service
  datasource:
    url: jdbc:mysql://localhost:3306/proddb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
